



###


GET http://localhost:8090/api/v1/bank/get  HTTP/1.1


###

GET http://localhost:8090/api/v1/bank/get2/665543a55d218627f6672186  HTTP/1.1


###

GET http://localhost:8090/api/v1/bank/instalment/list  HTTP/1.1


###

GET http://localhost:8090/api/v1/bank/cma/test  HTTP/1.1


###


GET http://localhost:8090/api/v1/bank/instalment/list?companyname=DGB대구은행  HTTP/1.1



####


GET http://127.0.0.1:8090/api/v1/bank/instalment/get/d1f2badd0918fcf04d2f06e048699b0f  HTTP/1.1



###


GET http://127.0.0.1:8090/api/v1/bank/deposit/list?bank_name=전북은행&period=24 HTTP/1.1


###



GET http://127.0.0.1:8090/api/v1/bank/cma/test HTTP/1.1



###


GET http://localhost:8090/api/v1/bank/deposit/get/75f7697bb28a2d35a6cc31be3a18d3da  HTTP/1.1




###


GET http://localhost:8090/api/v1/bank/deposit/top3  HTTP/1.1


###


GET http://localhost:8090/api/v1/bank/instalment/list?page=1  HTTP/1.1



###

POST http://127.0.0.1:8090/api/v1/bank/custom HTTP/1.1
Content-Type: application/json

{
    "period": "24",
    "targetAmount": 10000000,
    "youth": true,
    "mainBank": "신한은행"
    
}



###

POST http://127.0.0.1:8090/api/v1/bank/recommand/deposit HTTP/1.1
Content-Type: application/json

{
    "period": "24",
    "targetAmount": 30000000,
    "vulnerable_social_group": "N",
    "young": "Y",
    "soldier": "N",
    "children": "Y",
    "business": "N",
    "old":"N",
    "monthlyAmount": 2000000 
}



###


GET http://localhost:8090/api/v1/bank/deposit/list/test  HTTP/1.1