




###


GET http://localhost:8090/api/v1/card/get/3977  HTTP/1.1



###

GET http://localhost:8090/api/v1/card/list?benefits=간편결제,쇼핑  HTTP/1.1


###

GET http://localhost:8090/api/v1/card/test  HTTP/1.1




###


GET http://localhost:8090/api/v1/card/info/list  HTTP/1.1