




###


GET http://localhost:8090/api/v1/card/get/10071  HTTP/1.1



###

GET http://localhost:8090/api/v1/card/list?code=SH  HTTP/1.1


###

GET http://localhost:8090/api/v1/card/test  HTTP/1.1




###


GET http://localhost:8090/api/v1/card/info/list  HTTP/1.1


###

GET http://localhost:8090/api/v1/card/test/max  HTTP/1.1